### ISSUE TITLE
docker volume isn't writable

### ISSUE THREAD

**Issue by HelioNeves** [HelioNeves/os-cloud#1]
When inside the docker image, you can't write in the docker volume.

> sudo seems working

**Comment by TheGabrielRS** [comment]
there are a few ways to correct this, I'm investigating and will make a update on the Dockerfile soon

**Comment by TheGabrielRS** [comment]
#2 and https://github.com/HelioNeves/os-cloud/commit/b86951f057e4c025f211ad38c971c5eb8632b51a closes this issue
